# ===================================================================
# Spring Boot configuration
#
server:
  port: 9090
spring:
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    open-in-view: false
  threads:
    virtual:
      enabled: true

# ===================================================================
# App configuration properties
#
app:
  name: MOVIE-SERVICE
  movie-api-path-prefix: /movie-service
  enable-log-request-http: ${APP_ENABLE_LOG_REQUEST:true}
  security:
    server-key: ${APP_SERVER_KEY:Base@2024}
    filter:
      authentication: false
      authorization: false
    api-whitelist: /
    jwt:
      secret-key: ${APP_JWT_SECRET_KEY:52344E62DC399D1A15AC51A65F1DE}
      access-expire: 1440
      refresh-expire: 60
  task:
    executor:
      enable: true

datasource:
  default:
    enable: false
    jdbc-url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/movie}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:movie}
    password: ${POSTGRES_PASSWORD:movie@2025}
    minimum-idle: 10
    maximum-pool-size: 50
    idle-timeout: 600000
    max-lifetime: 1800000
    schema: ${POSTGRES_SCHEMA:movie}
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      use_sql_comments: true

messaging:
  kafka:
    enable: false
    producer:
      bootstrap-servers: localhost:9092
      delivery-timeout: 20000
      request-timeout: 10000
      retries: 3
    consumer:
      bootstrap-servers: localhost:9092
      group-id: movie-service
      max-poll-interval-ms: 40000
      enable-auto-commit: true
      auto-commit-interval: 1000
    listener:
      ack-mode: batch

cache:
  app-cache: ${app.name}
  internal:
    enable: true
    caffeine:
      spec: maximumSize=10000, expireAfterWrite=60s, recordStats, weakKeys, weakValues

logging:
  level:
    com.hit: debug
    org:
      apache:
        kafka:
          clients:
            consumer: debug
      springframework:
        kafka:
          listener: debug
